### ISSUE TITLE
[BUG] GetTriples limit doesn't work beyond limit=200

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/api-r#2]
**Describe the bug**
GetTriples("Class", limit=200) works, limit={201,300,500} returns empty list

**Additional context**
Could be related to bug seen in REST API.

**Comment by shifucun** [comment]
This is due to mixer returning snake case response when query from Bigquery. This is fixed by https://github.com/datacommonsorg/mixer/pull/28

**Comment by DragonEarin** [comment]
Makeit work
